export const API_CONFIG = {
    BASE_URL: 'http://localhost:8000/quotes',
    MAX_QUOTE_COUNT: 3000,
    MAX_SIMILAR_QUOTE_COUNT: 30,
    MAX_SIMILAR_QUOTE_DISTANCE: 0.7,
    REQUEST_INTERVAL: 50,
    REQUEST_CHECK_INTERVAL: 1000,
};

export const COLORS = {
    HIGHLIGHT: '#3b82f6'
};

export const CANVAS_CONFIG = {
    DEFAULT_SCALE: 200,
    MIN_SCALE: 50,
    MAX_SCALE: 2000,
    ZOOM_FACTOR: 1.1,
}; 